### ISSUE TITLE
Site wtf.solarma.it is rendering bad

### ISSUE THREAD

**Issue by gmacario** [wtf-next/wtf-next.github.com#1]

**Comment by gmacario** [comment]
**WORKAROUND**: View the slides locally with the following commands:
- Download https://github.com/neskov7/wtfweb/archive/v1.0.zip
- Unzip the downloaded file
- Open `wtfweb-1.0/index.html` from a web browser

**Comment by umbopepato** [comment]
@gmacario presentational website renders bad because it fails to load some of the necessary libraries ([http://wtf.solarma.it/jquery.fullpage.min.js/](http://wtf.solarma.it/jquery.fullpage.min.js/), [http://wtf.solarma.it/jquery.fullPage.min.css](http://wtf.solarma.it/jquery.fullPage.min.css)). Can you please check the presence of those files in the web server you setted up?

**Comment by gmacario** [comment]
Thanks @umbho!

The problem was that the upstream repo https://github.com/neskov7/wtfweb was likely created on a (Windows?) machine with a case-insensitive filesystem.

I have successfully deployed https://github.com/wtf-next/wtf-next.github.com/issues/3 and the problem is gone.

**Comment by gmacario** [comment]
I have also sent a PR upstream to @neskov7 - See https://github.com/neskov7/wtfweb/pull/1
